Repository tryber/sd-013-a-project-recipes-app, pull requests merged in 2021-09, with the labels that each got.

#55 [GRUPO 26] - Setup do Projeto
  describe-only.png
  only-all-green.png
  package-lock.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  pull-request-para-branch-do-grupo.png
  src/App.css
  src/App.js
  src/index.css
  src/index.js
  src/serviceWorker.js
Labels: good first issue

#58 provider setup browserRouter setup
  src/App.css
  src/App.js
  src/contextAPI/Context.js
  src/contextAPI/appProvider.js
Labels: code-review

#61 [ Grupo 11 ] Main group 11 Dev
  README.md
  package-lock.json
  src/App.js
  src/Provider/Provider.js
  src/Routes.js
  src/components/Header.jsx
  src/context/myContext.js
  src/index.js
  src/pages/Drinks.jsx
  src/pages/Foods.jsx
  src/pages/Login.jsx
  src/pages/Perfil.jsx
  src/services/index.js
Labels: code-review

#53 [ Group 5 ] Adiciona requisito 2 ao 8
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Comidas.js
  src/pages/Login.js
  src/reducers/index.js
  src/store/index.js
  src/test/Login.test.js
  src/test/RenderWithRouter.js
Labels: code-review

#75 [GRUPO 3] REQUISITO 11
  cypress/integration/header_spec.js
  src/App.js
  src/Pages/Perfil.jsx
  src/components/Header.js
Labels: code-review

#90 [GRUPO 3] REQUISITO 10
  cypress/integration/header_spec.js
  src/App.js
  src/Pages/ RecipesMade.jsx
  src/Pages/Drinks.jsx
  src/Pages/DrinksByIngredient.jsx
  src/Pages/ExploreDrinks.jsx
  src/Pages/ExploreFood.jsx
  src/Pages/ExploreScreen.jsx
  src/Pages/FavoriteRecipes.jsx
  src/Pages/Food.jsx
  src/Pages/FoodsByIngredient.jsx
  src/Pages/FoodsByOrigin.jsx
  src/Pages/Perfil.jsx
  src/components/Header.js
Labels: code-review

#91 [GRUPO 12] Requisitos 2 ao 5 - Resolvidos
  package-lock.json
  package.json
  src/App.js
  src/context/RecipesContext.js
  src/index.js
  src/pages/LoginPage.jsx
  src/pages/pages-css/LoginPage.css
Labels: code-review

#112 [GRUPO 12] Requisitos 6, 7 e 8 - FINALIZADOS
  src/pages/LoginPage.jsx
Labels: code-review

#120 [Grupo 2] Solves footer
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/index.js
  src/pages/Drinks.jsx
  src/pages/ExploreAll.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksByIngredient.jsx
  src/pages/ExploreFoodByOrigin.jsx
  src/pages/ExploreFoods.jsx
  src/pages/ExploreFoodsByIngredient.jsx
  src/pages/Foods.jsx
  src/pages/User.jsx
Labels: code-review

#129 [GRUPO 3] Requisito 13
  cypress/integration/header_search_bar_spec.js
  src/Pages/Food.jsx
  src/components/SearchBar.js
Labels: code-review

#136 [GRUPO 26] - Requisitos 1 ao 8 (Tela de Login)
  src/App.js
  src/helpers/renderWithReduxAndRouter.js
  src/pages/FoodRecipes.jsx
  src/pages/Login.jsx
  src/tests/App.test.js
  src/tests/Login.test.js
Labels: code-review

#138 Group 12 develop wesley requisito 25
  src/App.js
  src/context/RecipesProvider.js
  src/pages/CocktailRecipePage.jsx
  src/pages/MealRecipePage.jsx
  src/services/theCockTailDB_API.js
  src/services/theMealDB_API.js
Labels: code-review

#148 [ Group 20 ] Header Complemento
  src/App.js
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/pages/Drinks.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreFoods.jsx
  src/pages/ExploreIngredients.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Foods.jsx
  src/pages/Profile.jsx
  src/pages/RecipesDone.jsx
  src/redux/actions/index.jsx
  src/redux/reducers/functionsReducer.jsx
  src/redux/reducers/index.jsx
  src/styles/header.css
  src/styles/search.css
  src/utils/getPlaceholder.jsx
Labels: code-review

#150 [ Main group 6 ] fix requirement 10
  src/Routes.jsx
  src/components/Header.js
Labels: code-review

#160 [Grupo 5] Requisitos 2, 3 e 4
  src/App.js
  src/context/Provider.js
  src/context/RecipeContext.js
  src/index.js
  src/pages/Login.js
Labels: code-review

#163 Requisito 6, 7 e 8
  src/App.js
  src/pages/Login.js
Labels: code-review

#157 Group 12 develop wesley req 27 ao 32
  src/components/RecipesCards.jsx
  src/context/RecipesProvider.js
  src/pages/CocktailRecipePage.jsx
  src/pages/MealRecipePage.jsx
  src/services/theCockTailDB_API.js
  src/services/theMealDB_API.js
Labels: code-review

#165 Requisitos 9, 11, 12, 13 e 14
  src/App.js
  src/components/Header.js
  src/components/SearchBar.js
  src/context/Provider.js
  src/pages/Drinks.js
  src/pages/Explore.js
  src/pages/Foods.js
  src/pages/Profile.js
  src/pages/index.js
  src/styles/Header.css
Labels: code-review

#167 Adiciona o SearchBar no local correto
  cypress/integration/header_search_bar_spec.js
  src/Pages/Food.jsx
  src/components/Header.js
  src/components/SearchBar.js
Labels: code-review

#156 Footer incompleto
  src/App.js
  src/components/ExploreCocktail.jsx
  src/components/ExploreCocktailIngredients.jsx
  src/components/ExploreMeal.jsx
  src/components/ExploreMealIngredients.jsx
  src/components/ExploreMealLocation.jsx
  src/components/Footer.jsx
  src/components/components-css/footer.css
  src/pages/CocktailRecipePage.jsx
  src/pages/ExplorePage.jsx
  src/pages/MealRecipePage.jsx
  src/pages/ProfilePage.jsx
Labels: code-review

#180 [ Main group 6 ] Ending Login
  src/hooks/index.js
  src/pages/Login.js
Labels: code-review

#183 Group 12 develop refatorando 2
  README.md
  src/App.js
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/RecipeCard.jsx
  src/components/Searchbar.jsx
  src/components/styles/footer.css
  src/context/RecipesProvider.js
  src/pages/CocktailRecipePage.jsx
  src/pages/ExplorePage.jsx
  src/pages/LoginPage.jsx
  src/pages/MealRecipePage.jsx
  src/pages/styles/LoginPage.css
  src/services/recipeAPI.js
Labels: code-review

#188 Adiciona requisito 5
  src/Pages/Login.jsx
  src/context/Context.js
  src/context/Provider.js
  src/index.js
Labels: code-review

#195 [GRUPO 3] Requisito 14
  cypress/integration/header_search_bar_spec.js
  src/components/SearchBar.js
  src/context/Context.js
Labels: code-review

#205 [ Grupo 5 ] Requisitos até 24
  src/App.js
  src/components/Card.js
  src/components/Footer.js
  src/components/Header.js
  src/components/RecipesList.js
  src/components/SearchBar.js
  src/context/Provider.js
  src/context/RecipeContext.js
  src/index.js
  src/pages/DoneRecipes.js
  src/pages/DrinkDetails.js
  src/pages/DrinkExplore.js
  src/pages/DrinkExploreIngredients.js
  src/pages/DrinkInProgress.js
  src/pages/Drinks.js
  src/pages/Explore.js
  src/pages/FavoriteRecipes.js
  src/pages/FoodDetails.js
  src/pages/FoodExplore.js
  src/pages/FoodExploreIngredients.js
  src/pages/FoodExploreLocal.js
  src/pages/FoodInProgress.js
  src/pages/Foods.js
  src/pages/Login.js
  src/pages/Profile.js
  src/pages/index.js
  src/styles/Footer.css
  src/styles/Header.css
Labels: code-review

#199 Adiciona requisito 6
  src/Pages/Login.jsx
Labels: code-review

#201 [Group 20 ] Tela de Perfil
  src/pages/Profile.jsx
  src/pages/index.jsx
  src/redux/store/index.jsx
  src/styles/profile.css
Labels: code-review

#216 Grupo 12 Refatorando footer
  src/components/Footer.jsx
Labels: code-review

#210 [GRUPO 3] Requisito 15
  cypress/integration/header_search_bar_spec.js
  src/components/SearchBar.js
  src/context/Context.js
Labels: code-review

#247 [GRUPO 26] - Add search bar into header
  src/App.js
  src/components/Header.jsx
  src/tests/SearchBar.test.js
Labels: code-review

#245 Main group 24 dev fix bugs
  src/components/ButtonCategoryDrinks.jsx
  src/components/ButtonCategoryMeals.jsx
  src/components/DrinkCard.jsx
  src/components/MealCard.jsx
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
  src/redux/reducers/user.js
  src/redux/store/index.js
  src/styles/detalhes.css
Labels: code-review

#260 [GRUPO 26] - Cria as rotas e adiciona comentários
  cypress/integration/header_spec.js
  src/App.js
  src/components/Header.jsx
  src/pages/Details.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksIngr.jsx
  src/pages/ExploreFoods.jsx
  src/pages/ExploreFoodsArea.jsx
  src/pages/ExploreFoodsIngr.jsx
  src/pages/FoodRecipes.jsx
  src/pages/Profile.jsx
  src/pages/Recipes.jsx
  src/pages/index.js
Labels: bug, code-review

#265 até requisito 46 (bug no 40)
  src/components/IngredientList.jsx
  src/components/ShareAndFavoriteButtons.jsx
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
  src/redux/reducers/user.js
  src/redux/store/index.js
Labels: code-review

#236 Group 12 develop wesley refatorando provider
  src/context/RecipesProvider.js
  src/pages/CocktailRecipePage.jsx
  src/pages/MealRecipePage.jsx
  src/services/recipeAPI.js
  src/services/theCockTailDB_API.js
  src/services/theMealDB_API.js
Labels: code-review

#278 consertado requisito 40
  src/pages/DetalhesBebida.js
Labels: code-review

#69 [Group 27] Menu inferior
  package-lock.json
  src/Components/MenuInferior.js
  src/styles/MenuInferior.css
Labels: code-review

#284 [Group 24] Testes página de detalhes
  src/tests/RecipeDetails.test.js
Labels: code-review

#279 [GRUPO 3] Requisito 16
  cypress/integration/header_search_bar_spec.js
  src/App.js
  src/Pages/RecipeDetail.jsx
  src/Pages/RecipeDetailCard.jsx
  src/components/SearchBar.js
  src/context/Provider.js
Labels: code-review

#302 [Group 27] menuinferior 2
  src/Pages/Drinks.jsx
  src/Pages/DrinksExplorer.jsx
  src/Pages/Explorer.jsx
  src/Pages/ExplorerByIng.jsx
  src/Pages/FoodsByLocal.jsx
  src/Pages/FoodsExplorer.jsx
  src/Pages/Profile.jsx
  src/Pages/Recipes.jsx
Labels: code-review

#304 feito detalhes de comidas
  src/tests/RecipeDetails.test.js
Labels: code-review

#305 resolvendo bugs de bebidas em progresso localStorage
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
  src/redux/reducers/user.js
Labels: code-review

#315 [GRUPO 3] Requisito 17
  cypress/integration/header_search_bar_spec.js
  src/Pages/Drinks.jsx
  src/Pages/Food.jsx
  src/Pages/RecipeDetail.jsx
  src/components/Card.js
  src/components/RecipeDetailCard.jsx
Labels: code-review

#318 Adiciona requisitos do 70 ao 73
  src/App.js
  src/Pages/Area.jsx
  src/Pages/ExploreDrinks.jsx
  src/Pages/ExploreFood.jsx
  src/components/ButtonsExplorer.jsx
Labels: code-review

#325 [GRUPO 3] Requisito 18
  cypress/integration/header_search_bar_spec.js
  src/Pages/Drinks.jsx
  src/Pages/Food.jsx
  src/components/SearchBar.js
Labels: code-review

#351 Requisitos 33 e 34
  src/components/Loading.js
  src/components/RecommendedCard.js
  src/components/RecommendedList.js
  src/context/Provider.js
  src/pages/Details.js
Labels: code-review

#352 Requisito 35
  src/pages/Details.js
Labels: code-review

#338 Group 12 develop wesley req 54 ao 59
  package-lock.json
  package.json
  src/components/MakeRecipesPageCards.jsx
  src/components/styles/cards.css
  src/pages/MakeRecipesPage.jsx
Labels: code-review

#349 [ Main group 6 ] Refactoring and solving reqs 33 to 36
  cypress/integration/recipe_detail_spec.js
  src/pages/DrinkDetails.js
  src/pages/MealDetails.js
  src/pages/Perfil.js
  src/services/index.js
Labels: code-review

#345 [ Group 20 ] Tela de Explorar comidas por area
  src/App.js
  src/components/Header.jsx
  src/pages/Drinks.jsx
  src/pages/ExploreFoods.jsx
  src/pages/ExploreFoodsArea.jsx
  src/pages/Foods.jsx
  src/pages/NotFound.jsx
  src/pages/index.jsx
  src/redux/actions/index.jsx
  src/redux/reducers/functionsReducer.jsx
  src/services/requests.js
  src/styles/explore.css
  src/styles/header.css
  src/styles/itemCard.css
Labels: code-review

#374 [ Group 20 ] alterando botoes de link para button
  src/App.js
  src/components/Header.jsx
  src/components/RecipeCard.jsx
  src/pages/Drinks.jsx
  src/pages/ExploreDrinks.jsx
  src/redux/actions/index.jsx
  src/redux/reducers/functionsReducer.jsx
  src/styles/explore.css
  src/styles/itemCard.css
Labels: code-review

#396 [GRUPO 12] TELA DE EXPLORAR - Requisitos 67-69 - OK
  src/pages/ExplorePage.jsx
Labels: code-review

#398 [GRUPO 3] -Requisito 82 e 84
  src/Pages/Perfil.jsx
Labels: code-review

#402 [grupo 30] requisito 10
  src/App.js
  src/Pages/Area.jsx
  src/Pages/FoodsByArea.jsx
Labels: code-review

#423 [Grupo 5] Requisitos até 53
  src/App.css
  src/App.js
  src/components/ButtonFavorite.js
  src/components/ButtonFinish.js
  src/components/CardDone.js
  src/components/IngredientsCheckbox.js
  src/components/SearchBar.js
  src/context/Provider.js
  src/pages/Details.js
  src/pages/DetailsInProgress.js
  src/pages/DoneRecipes.js
  src/pages/DrinkInProgress.js
  src/pages/Drinks.js
  src/pages/FoodInProgress.js
  src/pages/Foods.js
  src/pages/NotFound.js
  src/pages/index.js
  src/services/setDoneRecipes.js
  src/styles/ButtonFinish.css
  src/styles/Card.css
  src/styles/Details.css
  src/styles/DoneRecipes.css
  src/styles/Drinks.css
  src/styles/Foods.css
Labels: code-review

#432 Main group 24 dev fixbug
  src/components/FilterButtonsDonesRecipes.jsx
  src/functions/index.jsx
  src/pages/DetalhesBebida.js
Labels: code-review

#418 Group 12 develop wesley req 70 ao 74
  src/App.js
  src/components/ExploreCocktail.jsx
  src/components/ExploreMeal.jsx
  src/pages/ExploreRecipesPage.jsx
  src/services/recipeAPI.js
Labels: code-review

#434 [Grupo 5] Requisitos 54, 55, 56 e 57
  src/pages/DoneRecipes.js
Labels: code-review

#436 [Grupo 24] Testes de receitas em progresso
  src/tests/RecipeInProgress.test.js
  src/tests/Searchbar.test.js
Labels: code-review

#452 Grupo5 req58e59
  src/components/CardDone.js
  src/pages/DoneRecipes.js
  src/services/setDoneRecipes.js
  src/styles/CardDone.css
Labels: code-review

#441 [GRUPO 3] REQUISITOS 83, 85 E 86
  cypress/integration/header_spec.js
  src/Pages/Perfil.jsx
Labels: code-review

#458 Requisitos 60, 61, 62, 63, 64, 65 e 66
  src/components/ButtonFavorite.js
  src/components/CardFavorite.js
  src/context/Provider.js
  src/pages/FavoriteRecipes.js
  src/styles/CardDone.css
  src/styles/Details.css
  src/styles/DoneRecipes.css
  src/styles/Drinks.css
  src/styles/Foods.css
Labels: code-review

#464 Requisitos 82, 83, 84, 85, 86 e 87
  src/pages/Profile.js
Labels: code-review

#460 [GRUPO 3] Requisito 87
  src/Pages/Perfil.jsx
Labels: code-review

#468 requisitos 70-74 finalizados
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarComidas.js
  src/pages/Perfil.js
Labels: code-review

#473 [Grupo 25] req 44 45 46
  cypress/integration/recipe_detail_spec.js
  src/components/RecipeDetails.js
  src/context/RecipesContextProvider.js
  src/functions/toggleFavoriteBtn.js
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
Labels: code-review

#461 Group 12 develop wesley req 78 ao 81
  src/App.js
  src/pages/ExploreRecipesAreaPage.jsx
  src/pages/NotFound.jsx
  src/services/recipeAPI.js
Labels: code-review

#476 [GRUPO 12][TELA DE EXPLORAR POR INGREDIENTES] Requisitos 75 ao 77
  src/App.js
  src/components/DetailsIcons.jsx
  src/components/ExploreMealIngredients.jsx
  src/context/RecipesProvider.js
  src/pages/CocktailRecipePage.jsx
  src/pages/DetailsRecipePage.jsx
  src/pages/ExploreIngredients.jsx
  src/pages/MealRecipePage.jsx
  src/pages/styles/DetailsRecipePage.css
  src/services/exploreIngredientsEndPointsCall.js
Labels: code-review

#492 [ Main group 6 ] Solving from req 74 to 77
  src/components/ExploreButtons.js
  src/components/IngredientCard.js
  src/components/IngredientsBox.js
  src/context/Provider.js
  src/pages/Drinks.js
  src/pages/IngredientsDrinksExplore.js
  src/pages/IngredientsMealsExplore.js
  src/pages/Meals.js
  src/services/index.js
Labels: code-review

#494 requisitos 74-81 finalizados
  cypress/integration/test_coverage_spec.js
  src/App.js
  src/components/AreaDropdown.jsx
  src/components/IngredientsDrinkCard.jsx
  src/components/IngredientsMealCard.jsx
  src/pages/Bebidas.js
  src/pages/BebidasIngredientes.js
  src/pages/ComidaOrigem.js
  src/pages/Comidas.js
  src/pages/ComidasIngredientes.js
  src/pages/NotFound.js
  src/pages/index.js
  src/redux/reducers/drinks.js
  src/redux/reducers/meals.js
Labels: code-review

#495 [ Grupo 5 ] Correções, adaptações, susto, tristeza, alegria,...
  src/App.css
  src/App.test.js
  src/components/CardDone.js
  src/components/CardFavorite.js
  src/components/Carousel.js
  src/pages/Details.js
  src/pages/DoneRecipes.js
  src/pages/Login.js
  src/pages/NotFound.js
  src/tests/App.test.js
  src/tests/ButtonBegun.test.js
  src/tests/ButtonFavorite.test.js
  src/tests/ButtonFinish.test.js
  src/tests/Details.test.js
  src/tests/DoneRecipes.test.js
  src/tests/DrinkExplore.test.js
  src/tests/DrinkExploreIngredients.test.js
  src/tests/Drinks.test.js
  src/tests/Explore.test.js
  src/tests/FavoriteRecipes.test.js
  src/tests/FoodExplore.test.js
  src/tests/FoodExploreIngredients.test.js
  src/tests/Foods.test.js
  src/tests/Footer.test.js
  src/tests/Header.test.js
  src/tests/Loading.test.js
  src/tests/Login.test.js
  src/tests/NotFound.test.js
  src/tests/Profile.test.js
  src/tests/renderWithRouter.js
Labels: [ In Process ]

#511 [ Main Group 6 ] Fix progress page
  src/pages/DrinkDetails.js
  src/pages/DrinkInProgress.js
  src/pages/MealDetails.js
  src/pages/MealInProgress.js
Labels: code-review

#477 [GRUPO 26] - Tela de Detalhes
  src/App.js
  src/helpers/checkFavorite.js
  src/helpers/newRecipe.js
  src/helpers/renderIngredients.js
  src/helpers/renderRecs.js
  src/pages/Details.jsx
  src/pages/Progress.jsx
  src/pages/index.js
  src/redux/actions/index.js
  src/services/apiRequest.js
  src/styles/Details.css
Labels: enhancement, code-review

#520 Main group 24 dev receites feitas fixed
  cypress/integration/test_coverage_spec.js
  src/components/AreaDropdown.jsx
  src/components/FilterButtonsDonesRecipes.jsx
  src/pages/BebidaEmProgresso.js
  src/pages/ComidaEmProcesso.js
  src/pages/ReceitasFeitas.js
  src/redux/reducers/user.js
  src/redux/store/index.js
  src/tests/comidasBebidasIngredientes.test.js
  src/tests/doneRecipes.test.js
  src/tests/filterButtons.test.js
  src/tests/notFound.test.js
Labels: code-review

#515 Adiciona requisito 62
  src/Pages/FavoriteRecipes.jsx
Labels: code-review

#542 [GRUPO 3] requisito 47
  cypress/integration/recipe_in_progress_spec.js
  src/App.js
  src/Pages/RecipeDetail.jsx
  src/Pages/RecipesInProgress.jsx
  src/components/RecipeDetailCard.jsx
Labels: code-review

#480 Main group 28 murilo
  cypress/integration/recipe_detail_spec.js
  src/components/CarrouselRecomendations.js
  src/components/ComponentsRefeições/CardFavoriteRecipe.js
  src/components/ComponentsRefeições/FavoriteButtonFavoriteRecipes.js
  src/components/FavoriteButton.js
  src/components/FavoriteRecipesContent.js
  src/components/FilterRecipes.js
  src/components/ShareButton.js
  src/components/ShareIcon.js
  src/components/StartRecipe.js
  src/contextAPI/AppProvider.js
  src/localStorage/localStorageSaves.js
  src/pages/DrinkDetails.js
  src/pages/FavoriteRecipes.js
  src/pages/FoodDetails.js
Labels: code-review

#575 Adiciona requisitos 64 e 66 corrigidos
  src/Pages/FavoriteRecipes.jsx
Labels: code-review

#596 [GRUPO 26] Inprogress page
  src/components/FavoriteButton.jsx
  src/components/RenderCheckbox.jsx
  src/components/RenderIngredients.jsx
  src/components/SearchBar.jsx
  src/components/ShareButton.jsx
  src/helpers/newRecipe.js
  src/hooks/useIngredients.js
  src/pages/Details.jsx
  src/pages/Progress.jsx
  src/styles/Progress.css
  src/tests/Details.test.js
  src/tests/Progress.test.js
Labels: code-review

#602 [Grupo 26] Profile-page
  src/pages/Profile.jsx
  src/tests/Profile.test.js
Labels: code-review
